name: Build and Deploy to Fasthosts (FTP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/@v4
        with:
          node-version: "20"

      - name: Install dependencies
        : npm install

      - name: Build site
        run: npm run build

      - name: Upload dist to Fasthosts htdocs
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FASTHOSTS_FTP_SERVER }}
          username: ${{ secrets.FASTHOSTS_FTP_USERNAME }}
          password: ${{ secrets.FASTHOSTS_FTP_PASSWORD }}
          local-dir: dist/
          server-dir: htdocs/
          dangerous-clean-slate: true
